### PR TITLE
[Windows] Add support for custom callback schemes

### LINKED ISSUE #25: Windows Callback URI Scheme other than http://localhost
Hi like i mentioned here https://github.com/appwrite/sdk-for-flutter/issues/96#issuecomment-1309344071 I found a potential solution for the callback-uri-scheme.
With this package https://pub.dev/packages/desktop_webview_window we could open a WebView window and call the Auth Url after the login process a URL change to our callback-uri-scheme will happen this can be catched with a registration here `void addOnUrlRequestCallback(OnUrlRequestCallback callback);`.

For the transition time i would say that we implement it as an additional feature.

So if a callback-uri-scheme is provided which is not fitting this Constraints 
https://github.com/ThexXTURBOXx/flutter_web_auth_2/blob/a844877485169c7becca7bd5a62df762646386f0/flutter_web_auth_2/lib/src/flutter_web_auth_2_windows.dart#L66-L72

Use the in App WebView

If wanted I will provide an PR for this.

### LINKED ISSUE #73: Browser new window was not opened in windows platform
## Describe the bug
I used this library in windows. I already login the  **URL(' https://ip:port/login')** on chrome browser after i try to authenticate this URL **('https://ip:port/desktop_login') via windows app** but new login window was not displayed. 

**IP and Port was same**

**Chrome login URL :** https://ip:port/login
**Windows app login URL :** https://ip:port/desktop_login

## To Reproduce
**Steps to reproduce the behavior:**
1. Open Chrome
2. login this **https://ip:port/login**
3. once login process was completed on web after try to authenticate this URL **https://ip:port/desktop_login**
4. New window was not opened on windows platform

## Expected behavior
I need to open new login page

## Device (please complete the following information!)
 - Device: Dell Latitude
 - OS: Windows 10
 - Browser: Chrome
 - `flutter_web_auth_2` version: [2.2.1]

### PR DESCRIPTION
**Pull request by Mino5531**
This PR adds supports for custom callback schemes during authentication on Windows, by opening a new instance of the application that displays a webview (Microsoft WebView2).

### Potential issues?
- Microsoft WebView2 must be installed or packaged with the app (preinstalled as part of Windows 11 and on some Windows 10 devices but not all) [Read more](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution)
- App developers must add the following code snippet to their main function to block the webview window from executing code twice 
```dart
void main(List<String> args) {
//Add this
  if (runWebViewTitleBarWidget(args)) {
    return;
  }
//---
  runApp(const MyApp());
}
```
- Will break the old way of using this library (using `http://localhost` as the scheme) as there will no longer be a local server that listens for calls

fixes #25 
And should also (hopefully) fix #73

### CODE REVIEW

**Comment by ThexXTURBOXx** [comment]
Thank you very much for your PR! I will review it probably during the weekend :)
The release will probably be version 4.0.0 then due to the breaking changes, but let's see

File: flutter_web_auth_2/example/lib/main.dart [hunk 1]
```diff
@@ -95,7 +101,7 @@ class MyAppState extends State<MyApp> {
 
       // Windows needs some callback URL on localhost
       req.response.write(
-        (Platform.isWindows || Platform.isLinux)
+        (Platform.isLinux)
```
Comment (ThexXTURBOXx) [inline flutter_web_auth_2/example/lib/main.dart:104]: `desktop_webview_window` claims to also work on Linux. Do you have a specific reason why you don't also enable it on that platform?

File: flutter_web_auth_2/example/lib/main.dart [hunk 2]
```diff
@@ -63,7 +64,12 @@ const html = '''
 </html>
 ''';
 
-void main() => runApp(const MyApp());
+void main(List<String> args) {
+  if (runWebViewTitleBarWidget(args)) {
+    return;
+  }
```
Comment (ThexXTURBOXx) [inline flutter_web_auth_2/example/lib/main.dart:70]: TODO for myself: This needs documentation

File: flutter_web_auth_2/example/pubspec.yaml [hunk 3]
```diff
@@ -8,9 +8,11 @@ environment:
 
 dependencies:
   cupertino_icons: ^1.0.3
+  desktop_webview_window: ^0.2.3
   flutter:
     sdk: flutter
-  flutter_web_auth_2: ^3.0.0
+  flutter_web_auth_2:
+    path: ../../flutter_web_auth_2
```
Comment (ThexXTURBOXx) [inline flutter_web_auth_2/example/pubspec.yaml:15]: Melos should do that automatically when calling `bootstrap`, but using a cleaner `pubspec_override`

File: flutter_web_auth_2/lib/flutter_web_auth_2.dart [hunk 4]
```diff
@@ -10,6 +10,7 @@ export 'src/options.dart';
 export 'src/unsupported.dart'
     if (dart.library.io) 'src/server.dart'
     if (dart.library.html) 'src/web.dart';
+export 'src/windows.dart';
```
Comment (ThexXTURBOXx) [inline flutter_web_auth_2/lib/flutter_web_auth_2.dart:13]: I believe this breaks the Web implementation, but I need to test properly. If it really breaks web, then we should really think about Linux support using the `desktop_webview_window` approach.

File: flutter_web_auth_2/lib/src/windows.dart [hunk 5]
```diff
@@ -0,0 +1,68 @@
...
+    final c = Completer<String>();
+    debugPrint(
+      '''Launching webview with url: $url, callbackUrlScheme: $callbackUrlScheme, tmpDir: ${(await getTemporaryDirectory()).path}''',
+    );
+    webview = await WebviewWindow.create(
+      configuration: CreateConfiguration(
+        windowHeight: 720,
+        windowWidth: 1280,
+        title: 'Authenticate',
+        titleBarTopPadding: Platform.isMacOS ? 20 : 0,
```
Comment (ThexXTURBOXx) [inline flutter_web_auth_2/lib/src/windows.dart:41]: I believe this is dead code, right? This file will never be relevant with MacOS

**Review by ThexXTURBOXx — CHANGES_REQUESTED** [review]
Here's a few things to think about or change. Thank you for your valuable PR!

File: flutter_web_auth_2/example/lib/main.dart (hunk 1 above)
Comment (Mino5531) [reply flutter_web_auth_2/example/lib/main.dart:104]: My original intention was to fix #73 because I had multiple users complaining about it. But theoretically it should be possible to use the same approach for Linux too. I haven't tested it though.

File: flutter_web_auth_2/example/pubspec.yaml (hunk 3 above)
Comment (Mino5531) [reply flutter_web_auth_2/example/pubspec.yaml:15]: Sorry I'm not familiar with melos and this was faster for me. I can revert this to the original if you'd like

File: flutter_web_auth_2/lib/src/windows.dart (hunk 5 above)
Comment (Mino5531) [reply flutter_web_auth_2/lib/src/windows.dart:41]: Yes you are right. I missed that sorry.

File: flutter_web_auth_2/example/lib/main.dart (hunk 1 above)
Comment (Mino5531) [reply flutter_web_auth_2/example/lib/main.dart:104]: The linux version of that library requires `webkit2gtk-4.1` as a dependency installed on the system, which might not be available on "older" systems (https://packages.ubuntu.com/search?keywords=webkit2gtk). How would you like to proceed?

Comment (ThexXTURBOXx) [reply flutter_web_auth_2/example/lib/main.dart:104]: Interesting, so there are different kinds of requirements on the webview approach.
I think, the best way to handle this is to let the developer decide which approach to take.
Maybe, it is possible to provide a configuration option within `FlutterWebAuth2Options` which has an enum (or something?) representing the approach that should be chosen.
Depending on that, `flutter_web_auth_2` chooses either your approach or the current one.
Do you think, that might be possible?

File: flutter_web_auth_2/example/pubspec.yaml (hunk 3 above)
Comment (ThexXTURBOXx) [reply flutter_web_auth_2/example/pubspec.yaml]: No problem! :) And thanks for reverting it already!

File: flutter_web_auth_2/example/lib/main.dart (hunk 1 above)
Comment (Mino5531) [reply flutter_web_auth_2/example/lib/main.dart:104]: I think something like that should be possible. I'll try to implement something like that. However the compiling computer will still require that dependency to be installed for linking/compiling.

Comment (ThexXTURBOXx) [reply flutter_web_auth_2/example/lib/main.dart:104]: Thank you very much! If you are stuck somehow, just let me know. Maybe I can help!

**Comment by ThexXTURBOXx** [comment]
Sorry for the late response. I have merged your changes and made sure that the "legacy" way and your new approach are both still callable.
I have also documented everything appropriately and will release `4.0.0-alpha.0` now. Thanks for contributing!
